mastername: testmaster
domain: example.com
netmask: 16
bridge: eno1
masterip: 10.10.90.120

calico_version: v3.18

image: bento/ubuntu-18.04

mastermemory: 2000
mastercpu: 2

nodememory: 2500
nodecpu: 2

