- name: testmaster
  ip: 10.10.90.120
  master: true
  cidr: 192.168.0.0/16

- name: testnode1
  ip: 10.10.90.121
  node: true

- name: testnode2
  ip: 10.10.90.122                      
  node: true

